### ISSUE TITLE
Stoped working after core update 2021.8.?

### ISSUE THREAD

**Issue by Newman820** [T3m3z/HA-Vestel-Component#2]
I was updating Home Assistant from 2021.5.x to 2021.8.6 and after that my Vestel integration stoped working.

Got error message - Integration ‘vessel’ not found.

**Comment by andylynch** [comment]
Home Assistant now expects a version fields in the manifest --  https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#version

I have an ugly but trivial patch to define this, and will raise a PR.

**Comment by T3m3z** [comment]
Sorry for the delay. I haven't had enough time to check this.

I fixed this now by adding the version field to the manifest. The commit also adds a new service which allows one to send key presses to the television.
