### ISSUE TITLE
Change TCP Port for TV

### ISSUE THREAD

**Issue by MrPePperNL** [T3m3z/HA-Vestel-Component#3]
Hello,

I tried to use this component on my Medion X15095 TV. When manually doing curl to post the commands the TV responds.

This TV is using port 56789 to accept the post commands.

However I cannot set this port in the configuration.

Can you help ?

**Comment by its-me-prash** [comment]
@T3m3z any help on the above?

**Comment by MrPePperNL** [comment]
I forgot about this, never received any response until now.

My vestel tv is stil in use, and i've written (copied) some scripts to use curl to mute f.e. when my doorbell rings.

Actually the py package needs to be changed and/or this integration needs to honor the port configuration option. Both beyond my knowledge.

Would love to use the py package and this integration.

**Comment by kinkamez** [comment]
Can i get an example curl command?

**Comment by T3m3z** [comment]
Sorry for a very long delay in answering. My TV also exposes HTTP server on that port (or actually 3 adjacent ports and TV selects active one on each boot randomly). Some of the configuration happens

Unfortunately I don't have time nor energy to do significant development for a TV which differs from my TV (debugging problems would be a headache).

But! If you know the URLs which to call, it might be possible to create command line switches for every function that you need (https://www.home-assistant.io/integrations/command_line/#switch) and then tie these together with Universal Media Player component ( https://www.home-assistant.io/integrations/universal/ ).

I hope that you succeed with this.

Best Regards, Temez

**Comment by MrPePperNL** [comment]
Hello Temez,

Yes i've been using the curl command line's to create the switches I need. For now it is ok for me to work with.

But still would love to have this working with the integration.

I will close the issue as it is not relevant to me anymore.
